### ISSUE TITLE
Register book data by searching by ISBN from an API

### ISSUE THREAD

**Issue by aburd** [aburd/sci-fi-books#5]
Registering new data sucks because we have to do it by hand. What if we could just get it from an API?
Maybe there's an existing API that can give us the data?
http://openlibrary.org/search.json?q=ursula+leguin 

- [x] A regex to only allow 11 or 13 digits (ISBN-11 or ISBN-13). Both work for the API endpoint.
- [x] Confirmation of book title and author before registration into database.
- [x] Asking if user would like to register another book.
- [x] Actually adding the book it to the database.

**Comment by shanedbutler** [comment]
I think hitting the API with an ISBN might be the best way to start since it can accurately select a book without having to search by author or title. I wrote up something that attempts this: [https://github.com/aburd/sci-fi-books/tree/enhance/more-bookz](https://github.com/aburd/sci-fi-books/tree/enhance/more-bookz)

It asks for the ISBN in the node.js console and interpolates it into the Open Library API endpoint for .json book data by ISBN. Not sure if it should be in the main js program or in some kind of admin program (maybe the main program is the admin program) I know we want to make a web front-end for all this. 

To finish this issue:

- A regex to only allow 11 or 13 digits (ISBN-11 or ISBN-13). Both work for the API endpoint.

- Confirmation of book title and author before registration into database.

- Asking if user would like to register another book.

- Actually adding the book it to the database.

**Comment by aburd** [comment]
@minidiscs 
You should open a draft PR
https://github.blog/2019-02-14-introducing-draft-pull-requests/

That way we can see the code diff

**Comment by aburd** [comment]
> It asks for the ISBN in the node.js console and interpolates it into the Open Library API endpoint for .json book data by ISBN. Not sure if it should be in the main js program or in some kind of admin program (maybe the main program is the admin program) I know we want to make a web front-end for all this.

This is pretty tight, but you'd have to have the ISBN on hand. 
Maybe we can make a CLI interface where you can search by a parameter of your choosing, with ISBN as one of the options.

> To finish this issue:

I think this is a feature on it's own. We should break this up into multiple issues!

**Comment by aburd** [comment]
I just reread your comment and finally got what you're trying to do and I have to say, it's a pretty sweet idea. I'm going to update the description.
